### ISSUE TITLE
install fails on AWS 2023 Linux with dnf on c5.2xlarge with AMI  ami-0e731c8a588258d0d

### ISSUE THREAD

**Issue by golharam** [awslabs/amazon-ebs-autoscale#73]
```
2024-03-19 16:04:14,867 - handlers.py[DEBUG]: start: modules-final/config-package-update-upgrade-install: running config-package-update-upgrade-install with frequency once-per-instance
2024-03-19 16:04:14,867 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-01201a3290231f327/sem/config_package_update_upgrade_install - wb: [644] 25 bytes
2024-03-19 16:04:14,868 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-01201a3290231f327/sem/config_package_update_upgrade_install (recursive=False)
2024-03-19 16:04:14,870 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-01201a3290231f327/sem/config_package_update_upgrade_install (recursive=False)
2024-03-19 16:04:14,870 - helpers.py[DEBUG]: Running config-package-update-upgrade-install using lock (<FileLock using file '/var/lib/cloud/instances/i-01201a3290231f327/sem/config_package_update_upgrade_install'>)
2024-03-19 16:04:14,870 - rhel.py[DEBUG]: Using DNF for package management
2024-03-19 16:04:14,871 - subp.py[DEBUG]: Running command ['dnf', '-y', 'install', 'jq', 'btrfs-progs', 'sed', 'wget', 'git', 'unzip', 'lvm2'] with allowed return codes [0] (shell=False, capture=False)
2024-03-19 16:04:22,370 - util.py[WARNING]: Failed to install packages: ['jq', 'btrfs-progs', 'sed', 'wget', 'git', 'unzip', 'lvm2']
2024-03-19 16:04:22,370 - util.py[DEBUG]: Failed to install packages: ['jq', 'btrfs-progs', 'sed', 'wget', 'git', 'unzip', 'lvm2']
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/cloudinit/config/cc_package_update_upgrade_install.py", line 104, in handle
    cloud.distro.install_packages(pkglist)
  File "/usr/lib/python3.9/site-packages/cloudinit/distros/rhel.py", line 66, in install_packages
    self.package_command("install", pkgs=pkglist)
  File "/usr/lib/python3.9/site-packages/cloudinit/distros/rhel.py", line 193, in package_command
    subp.subp(cmd, capture=False)
  File "/usr/lib/python3.9/site-packages/cloudinit/subp.py", line 335, in subp
    raise ProcessExecutionError(
cloudinit.subp.ProcessExecutionError: Unexpected error while running command.
Command: ['dnf', '-y', 'install', 'jq', 'btrfs-progs', 'sed', 'wget', 'git', 'unzip', 'lvm2']
Exit code: 1
Reason: -
Stdout: -
Stderr: -
2024-03-19 16:04:22,383 - cc_package_update_upgrade_install.py[WARNING]: 1 failed with exceptions, re-raising the last one
2024-03-19 16:04:22,384 - handlers.py[DEBUG]: finish: modules-final/config-package-update-upgrade-install: FAIL: running config-package-update-upgrade-install with frequency once-per-instance
2024-03-19 16:04:22,384 - util.py[WARNING]: Running module package-update-upgrade-install (<module 'cloudinit.config.cc_package_update_upgrade_install' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_package_update_upgrade_install.py'>) failed
2024-03-19 16:04:22,384 - util.py[DEBUG]: Running module package-update-upgrade-install (<module 'cloudinit.config.cc_package_update_upgrade_install' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_package_update_upgrade_install.py'>) failed
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/cloudinit/config/modules.py", line 231, in _run_modules
    ran, _r = cc.run(
  File "/usr/lib/python3.9/site-packages/cloudinit/cloud.py", line 67, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
  File "/usr/lib/python3.9/site-packages/cloudinit/helpers.py", line 185, in run
    results = functor(*args)
  File "/usr/lib/python3.9/site-packages/cloudinit/config/cc_package_update_upgrade_install.py", line 130, in handle
    raise errors[-1]
  File "/usr/lib/python3.9/site-packages/cloudinit/config/cc_package_update_upgrade_install.py", line 104, in handle
    cloud.distro.install_packages(pkglist)
  File "/usr/lib/python3.9/site-packages/cloudinit/distros/rhel.py", line 66, in install_packages
    self.package_command("install", pkgs=pkglist)
  File "/usr/lib/python3.9/site-packages/cloudinit/distros/rhel.py", line 193, in package_command
    subp.subp(cmd, capture=False)
  File "/usr/lib/python3.9/site-packages/cloudinit/subp.py", line 335, in subp
    raise ProcessExecutionError(
cloudinit.subp.ProcessExecutionError: Unexpected error while running command.
Command: ['dnf', '-y', 'install', 'jq', 'btrfs-progs', 'sed', 'wget', 'git', 'unzip', 'lvm2']
Exit code: 1
Reason: -
Stdout: -
Stderr: -
2024-03-19 16:04:22,387 - modules.py[DEBUG]: Running module write-files-deferred (<module 'cloudinit.config.cc_write_files_deferred' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_write_files_deferred.py'>) with frequency once-per-instance
2024-03-19 16:04:22,387 - handlers.py[DEBUG]: start: modules-final/config-write-files-deferred: running config-write-files-deferred with frequency once-per-instance
```

**Comment by golharam** [comment]
Not sure why this is failed.  Earlier in cloud-init.log, I see:
```
2024-03-19 16:04:14,551 - helpers.py[DEBUG]: Running config-yum-variables using lock (<FileLock using file '/var/lib/cloud/instances/i-01201a3290231f327/sem/config_yum_variables'>)
2024-03-19 16:04:14,551 - cc_yum_variables.py[INFO]: handling yum-variables
2024-03-19 16:04:14,551 - cc_yum_variables.py[INFO]: cfg = {'packages': ['jq', 'btrfs-progs', 'sed', 'wget', 'git', 'unzip', 'lvm2'], 'repo_update': True, 'repo_upgrade': 'all', 'runcmd': ['curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv
2.zip"', 'unzip -q /tmp/awscliv2.zip -d /tmp && /tmp/aws/install', 'EBS_AUTOSCALE_VERSION=0a8af79', 'cd /opt && git clone https://github.com/awslabs/amazon-ebs-autoscale.git', 'cd /opt/amazon-ebs-autoscale && git checkout $EBS_AUTOSCALE_VERSION', 'sh /opt/amazon-ebs-autosc
ale/install.sh -d /dev/xvdb -f lvm.ext4 -m /scratch 2>&1 > /var/log/ebs-autoscale-install.log'], 'power_state': {'delay': 'now', 'mode': 'reboot', 'message': 'Rebooting machine to apply SELinux kernel commandline setting', 'condition': 'test -f /run/cloud-init-selinux-rebo
ot'}, 'write_metadata': [{'path': '/etc/dnf/vars/awsregion', 'data': [{'identity': 'region'}, 'default']}, {'path': '/etc/dnf/vars/awsdomain', 'data': [{'metadata': 'services/domain'}, 'amazonaws.com']}], '_log': ['[loggers]\nkeys=root,cloudinit\n\n[handlers]\nkeys=console
Handler,cloudLogHandler\n\n[formatters]\nkeys=simpleFormatter,arg0Formatter\n\n[logger_root]\nlevel=DEBUG\nhandlers=consoleHandler,cloudLogHandler\n\n[logger_cloudinit]\nlevel=DEBUG\nqualname=cloudinit\nhandlers=\npropagate=1\n\n[handler_consoleHandler]\nclass=StreamHandle
r\nlevel=WARNING\nformatter=arg0Formatter\nargs=(sys.stderr,)\n\n[formatter_arg0Formatter]\nformat=%(asctime)s - %(filename)s[%(levelname)s]: %(message)s\n\n[formatter_simpleFormatter]\nformat=[CLOUDINIT] %(filename)s[%(levelname)s]: %(message)s\n', "[handler_cloudLogHandl
er]\nclass=FileHandler\nlevel=DEBUG\nformatter=arg0Formatter\nargs=('/var/log/cloud-init.log', 'a', 'UTF-8')\n", '[handler_cloudLogHandler]\nclass=handlers.SysLogHandler\nlevel=DEBUG\nformatter=simpleFormatter\nargs=("/dev/log", handlers.SysLogHandler.LOG_USER)\n'], 'log_c
fgs': [['[loggers]\nkeys=root,cloudinit\n\n[handlers]\nkeys=consoleHandler,cloudLogHandler\n\n[formatters]\nkeys=simpleFormatter,arg0Formatter\n\n[logger_root]\nlevel=DEBUG\nhandlers=consoleHandler,cloudLogHandler\n\n[logger_cloudinit]\nlevel=DEBUG\nqualname=cloudinit\nhan
dlers=\npropagate=1\n\n[handler_consoleHandler]\nclass=StreamHandler\nlevel=WARNING\nformatter=arg0Formatter\nargs=(sys.stderr,)\n\n[formatter_arg0Formatter]\nformat=%(asctime)s - %(filename)s[%(levelname)s]: %(message)s\n\n[formatter_simpleFormatter]\nformat=[CLOUDINIT] %
(filename)s[%(levelname)s]: %(message)s\n', "[handler_cloudLogHandler]\nclass=FileHandler\nlevel=DEBUG\nformatter=arg0Formatter\nargs=('/var/log/cloud-init.log', 'a', 'UTF-8')\n"]], 'output': {'all': '| tee -a /var/log/cloud-init-output.log'}, 'network': {'config': 'disabl
ed'}, 'datasource_list': ['Ec2', 'None'], 'datasource': {'Ec2': {'metadata_urls': ['http://169.254.169.254:80', 'http://[fd00:ec2::254]:80'], 'apply_full_imds_network_config': False}}, 'ssh_genkeytypes': ['ed25519', 'ecdsa'], 'users': ['default'], 'disable_root': True, 'mo
unt_default_fields': [None, None, 'auto', 'defaults,nofail', '0', '2'], 'resize_rootfs': 'noblock', 'resize_rootfs_tmp': '/dev', 'ssh_pwauth': False, 'preserve_hostname': False, 'cloud_init_modules': ['migrator', 'seed_random', 'bootcmd', 'write-files', 'write-metadata', '
growpart', 'resizefs', 'disk_setup', 'mounts', 'set_hostname', 'update_hostname', 'update_etc_hosts', 'ca-certs', 'rsyslog', 'selinux', 'users-groups', 'ssh'], 'cloud_config_modules': ['ssh-import-id', 'keyboard', 'locale', 'set-passwords', 'yum-variables', 'yum-add-repo',
 'ntp', 'timezone', 'disable-ec2-metadata', 'runcmd'], 'cloud_final_modules': ['package-update-upgrade-install', 'write-files-deferred', 'puppet', 'chef', 'mcollective', 'salt-minion', 'reset_rmc', 'refresh_rmc_and_interface', 'rightscale_userdata', 'scripts-vendor', 'scri
pts-per-once', 'scripts-per-boot', 'scripts-per-instance', 'scripts-user', 'ssh-authkey-fingerprints', 'keys-to-console', 'install-hotplug', 'phone-home', 'final-message', 'power-state-change'], 'def_log_file': '/var/log/cloud-init.log', 'syslog_fix_perms': ['syslog:adm', 
'root:adm', 'root:wheel', 'root:root'], 'vendor_data': {'enabled': True, 'prefix': []}, 'vendor_data2': {'enabled': True, 'prefix': []}}
2024-03-19 16:04:14,551 - cc_yum_variables.py[INFO]: No yum vars to delete
2024-03-19 16:04:14,551 - cc_yum_variables.py[INFO]: No yum vars to set
2024-03-19 16:04:14,551 - handlers.py[DEBUG]: finish: modules-config/config-yum-variables: SUCCESS: config-yum-variables ran successfully
```

**Comment by golharam** [comment]
Looks like btrfs-progs is not available on AWS Linux 2023?
```
$ sudo dnf -y install jq btrfs-progs sed wget git unzip lvm2
Last metadata expiration check: 0:15:30 ago on Tue Mar 19 16:04:21 2024.
Package jq-1.6-10.amzn2023.0.2.x86_64 is already installed.
No match for argument: btrfs-progs
Package sed-4.8-7.amzn2023.0.2.x86_64 is already installed.
Package wget-1.21.3-1.amzn2023.0.3.x86_64 is already installed.
Package git-2.40.1-1.amzn2023.0.1.x86_64 is already installed.
Package unzip-6.0-57.amzn2023.0.2.x86_64 is already installed.
Error: Unable to find a match: btrfs-progs
```

Referencing https://github.com/amazonlinux/amazon-linux-2023/issues/342.

**Comment by golharam** [comment]
Removing btrfs-progs from line 7 of https://github.com/awslabs/amazon-ebs-autoscale/blob/a55e7cc8913dd89e42b4668e4e8883209db26e9c/templates/cloud-init-userdata.yaml, and using lvm, all works fine.
